/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto;

import javax.swing.JOptionPane;

/**
 *
 * @author jonat
 */
public class DatosPedidos extends javax.swing.JFrame {

    /**
     * Creates new form DatosPedidos
     */
    public DatosPedidos() {
        PedidosClientes pedidosClientes = new PedidosClientes();
        initComponents();
        tablaPedidos.setModel(pedidosClientes.getMostrar());
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPedidos = new javax.swing.JTable();
        idPedido = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        idComponente = new javax.swing.JTextField();
        idClientePedido = new javax.swing.JTextField();
        btnCrearPedido = new javax.swing.JButton();
        btnBorrarPedido = new javax.swing.JButton();
        btnEditarPedido = new javax.swing.JButton();
        btnRegresarDePedidos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Código pedido");

        tablaPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaPedidos);

        idPedido.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        idPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idPedidoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setText("Pedidos");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Código cliente");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Componente");

        idComponente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        idComponente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idComponenteActionPerformed(evt);
            }
        });

        idClientePedido.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        idClientePedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idClientePedidoActionPerformed(evt);
            }
        });

        btnCrearPedido.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCrearPedido.setText("Crear pedido");
        btnCrearPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearPedidoActionPerformed(evt);
            }
        });

        btnBorrarPedido.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBorrarPedido.setText("Borrar pedido");
        btnBorrarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarPedidoActionPerformed(evt);
            }
        });

        btnEditarPedido.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEditarPedido.setText("Editar pedido");
        btnEditarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarPedidoActionPerformed(evt);
            }
        });

        btnRegresarDePedidos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRegresarDePedidos.setText("Regresar");
        btnRegresarDePedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarDePedidosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(idClientePedido, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idComponente, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnCrearPedido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBorrarPedido, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEditarPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRegresarDePedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(idPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(idClientePedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idComponente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCrearPedido)
                            .addComponent(btnEditarPedido))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBorrarPedido)
                            .addComponent(btnRegresarDePedidos)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idPedidoActionPerformed

    private void idComponenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idComponenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idComponenteActionPerformed

    private void idClientePedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idClientePedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idClientePedidoActionPerformed

    private void btnCrearPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearPedidoActionPerformed
        
        PedidosClientes pedidos = new PedidosClientes();
        try{
        pedidos.setCod_pedido(Integer.parseInt(idPedido.getText()));
        pedidos.setCod_clientes(Integer.parseInt(idClientePedido.getText()));
        pedidos.setCod_componenteElectrico(idComponente.getText());
        
        
        if(pedidos.getCrearPedido(pedidos)){
            JOptionPane.showMessageDialog(null, "Pedido  guardado");
            tablaPedidos.setModel(pedidos.getMostrar());
        }else{
            JOptionPane.showMessageDialog(null, "Error guardado");
        }
        }catch(Exception e){
             JOptionPane.showMessageDialog(null,"Debe ingresar datos validos para cada campo");
        }
    }//GEN-LAST:event_btnCrearPedidoActionPerformed

    private void btnEditarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarPedidoActionPerformed
         PedidosClientes pedidos = new PedidosClientes();
       try{
        pedidos.setCod_pedido(Integer.parseInt(idPedido.getText()));
        pedidos.setCod_clientes(Integer.parseInt(idClientePedido.getText()));
        pedidos.setCod_componenteElectrico(idComponente.getText());
        
        if(pedidos.getEditarPedido(pedidos)){
            JOptionPane.showMessageDialog(null, "Se edito el pedido");
            tablaPedidos.setModel(pedidos.getMostrar());
        }else{
            JOptionPane.showMessageDialog(null, "Error al editar los datos");
        }
       }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Debe ingresar datos validos para cada campo");
       }
    }//GEN-LAST:event_btnEditarPedidoActionPerformed

    private void btnBorrarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarPedidoActionPerformed
      PedidosClientes pedido = new PedidosClientes();
        
        pedido.setCod_pedido(Integer.parseInt(idPedido.getText()));
        if(pedido.getBorrarPedido(pedido)){
            JOptionPane.showMessageDialog(null, "Pedido eliminado");
            tablaPedidos.setModel(pedido.getMostrar());
        }else{
             JOptionPane.showMessageDialog(null, "No se pudo eliminar el pedido");
        }
    }//GEN-LAST:event_btnBorrarPedidoActionPerformed

    private void btnRegresarDePedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarDePedidosActionPerformed
       java.awt.EventQueue.invokeLater(() -> {
           new Inicio().setVisible(true);
       });
       
        hide();
    }//GEN-LAST:event_btnRegresarDePedidosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatosPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatosPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatosPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatosPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatosPedidos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrarPedido;
    private javax.swing.JButton btnCrearPedido;
    private javax.swing.JButton btnEditarPedido;
    private javax.swing.JButton btnRegresarDePedidos;
    private javax.swing.JTextField idClientePedido;
    private javax.swing.JTextField idComponente;
    private javax.swing.JTextField idPedido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaPedidos;
    // End of variables declaration//GEN-END:variables
}
